"""spelling correction in Proxy constraint

Revision ID: b5fefb492b78
Revises: f1a7dc15552d
Create Date: 2020-08-16 00:57:52.908312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fefb492b78'
down_revision = 'f1a7dc15552d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ip_address_constraint', 'proxy', ['ip_address'])
    op.drop_constraint('ip_adress_constraint', 'proxy', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ip_adress_constraint', 'proxy', ['ip_address'])
    op.drop_constraint('ip_address_constraint', 'proxy', type_='unique')
    # ### end Alembic commands ###
