version: "3.8"

services:

  scrapy:
    volumes:
      - type: bind
        source: ./import
        target: /import/scrapyanon
      - type: bind
        source: ..
        target: /src
    environment: 
      DEVELOPMENT: "true"
