"""initial setup

Revision ID: 006fcf03d9e4
Revises: cfa39fa6b9e3
Create Date: 2020-10-20 11:03:50.604299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006fcf03d9e4'
down_revision = 'cfa39fa6b9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
