"""initial setup

Revision ID: 03c05318ebc9
Revises: f6567e038fcb
Create Date: 2020-10-23 23:45:00.517381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c05318ebc9'
down_revision = 'f6567e038fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
