"""initial setup

Revision ID: 0c70aabcd3ee
Revises: c5ccbab73567
Create Date: 2020-10-24 01:03:29.894246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c70aabcd3ee'
down_revision = 'c5ccbab73567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
