"""initial setup

Revision ID: 0d5478ff5cc3
Revises: 006fcf03d9e4
Create Date: 2020-10-20 11:08:42.154249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5478ff5cc3'
down_revision = '006fcf03d9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
