"""initial setup

Revision ID: 0f8d2e1a7725
Revises: 25d9e0829a07
Create Date: 2020-10-27 00:51:42.441027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8d2e1a7725'
down_revision = '25d9e0829a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_hello',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('client_hello', sa.String(), nullable=False),
    sa.Column('updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_hello'),
    sa.UniqueConstraint('client_hello', name='client_hello_constraint')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('tor_fingerprint', sa.String(), nullable=True),
    sa.Column('tor_nickname', sa.String(), nullable=True),
    sa.Column('is_tor_exit_node', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', name='ip_address_constraint'),
    sa.UniqueConstraint('tor_fingerprint')
    )
    op.create_table('client_hello_proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_hello_id', sa.Integer(), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_hello_id'], ['client_hello.id'], ),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website', 'proxy_id', name='website_proxy_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_hello_proxy')
    op.drop_table('proxy')
    op.drop_table('client_hello')
    # ### end Alembic commands ###
