"""initial setup

Revision ID: 1306aad42810
Revises: b1e60342cc2e
Create Date: 2020-10-21 06:11:13.549256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1306aad42810'
down_revision = 'b1e60342cc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
