"""initial setup

Revision ID: 146f41971c10
Revises: deb834364bed
Create Date: 2020-10-21 02:47:52.733345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146f41971c10'
down_revision = 'deb834364bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
