"""initial setup

Revision ID: 1b39cfeaa1bd
Revises: dbd25c203031
Create Date: 2020-10-20 14:16:22.253740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b39cfeaa1bd'
down_revision = 'dbd25c203031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
