"""updated ClientHelloProxy columns

Revision ID: 787efc85c05c
Revises: 25faac7b8551
Create Date: 2021-06-07 12:51:11.196932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787efc85c05c'
down_revision = '25faac7b8551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_hello_proxy', sa.Column('ip_address', sa.Integer(), nullable=False))
    op.drop_constraint('website_proxy_constraint', 'client_hello_proxy', type_='unique')
    op.create_unique_constraint('website_ip_address_constraint', 'client_hello_proxy', ['website', 'ip_address'])
    op.drop_constraint('client_hello_proxy_client_hello_id_fkey', 'client_hello_proxy', type_='foreignkey')
    op.drop_constraint('client_hello_proxy_proxy_id_fkey', 'client_hello_proxy', type_='foreignkey')
    op.create_foreign_key(None, 'client_hello_proxy', 'proxy', ['ip_address'], ['id'])
    op.drop_column('client_hello_proxy', 'proxy_id')
    op.drop_column('client_hello_proxy', 'client_hello_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_hello_proxy', sa.Column('client_hello_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('client_hello_proxy', sa.Column('proxy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_hello_proxy', type_='foreignkey')
    op.create_foreign_key('client_hello_proxy_proxy_id_fkey', 'client_hello_proxy', 'proxy', ['proxy_id'], ['id'])
    op.create_foreign_key('client_hello_proxy_client_hello_id_fkey', 'client_hello_proxy', 'client_hello', ['client_hello_id'], ['id'])
    op.drop_constraint('website_ip_address_constraint', 'client_hello_proxy', type_='unique')
    op.create_unique_constraint('website_proxy_constraint', 'client_hello_proxy', ['website', 'proxy_id'])
    op.drop_column('client_hello_proxy', 'ip_address')
    # ### end Alembic commands ###
