"""'is_tor_exit_node' changed to 'source'

Revision ID: e176dd00520a
Revises: ed37fb95a840
Create Date: 2021-06-07 15:12:00.350306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e176dd00520a'
down_revision = 'ed37fb95a840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('source', sa.String(), nullable=False))
    op.drop_column('proxy', 'is_tor_exit_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('is_tor_exit_node', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('proxy', 'source')
    # ### end Alembic commands ###
