"""initial setup

Revision ID: 22878efaba7b
Revises: d55368111a8c
Create Date: 2020-10-24 23:57:27.806412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22878efaba7b'
down_revision = 'd55368111a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
