"""initial setup

Revision ID: 2551ccac947c
Revises: 3595ea5e11e1
Create Date: 2020-10-25 01:20:16.837254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2551ccac947c'
down_revision = '3595ea5e11e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
