"""initial setup

Revision ID: 27e7d54b2305
Revises: 3e639eb62152
Create Date: 2020-10-21 22:12:09.006456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e7d54b2305'
down_revision = '3e639eb62152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
