"""initial setup

Revision ID: 2b44cedd9dff
Revises: 75d685cc34ba
Create Date: 2020-10-23 10:12:08.693449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b44cedd9dff'
down_revision = '75d685cc34ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
