"""initial setup

Revision ID: 3595ea5e11e1
Revises: 22878efaba7b
Create Date: 2020-10-25 01:08:01.976217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3595ea5e11e1'
down_revision = '22878efaba7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
