"""initial setup

Revision ID: 3b0d7767f518
Revises: 604ecdf71b17
Create Date: 2020-10-21 07:44:23.770802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0d7767f518'
down_revision = '604ecdf71b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
