"""initial setup

Revision ID: 3e639eb62152
Revises: 962d74837db8
Create Date: 2020-10-21 10:51:08.446467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e639eb62152'
down_revision = '962d74837db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
