"""initial setup

Revision ID: 3ed76042baca
Revises: 6d9d9f198c36
Create Date: 2020-10-21 08:12:41.856291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed76042baca'
down_revision = '6d9d9f198c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
