"""initial setup

Revision ID: 3f9472532aa9
Revises: d197bd834291
Create Date: 2020-10-23 10:45:51.471517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9472532aa9'
down_revision = 'd197bd834291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
