"""initial setup

Revision ID: 404d2d085b85
Revises: 3ed76042baca
Create Date: 2020-10-21 10:12:58.675779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404d2d085b85'
down_revision = '3ed76042baca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
