"""initial setup

Revision ID: 406122598e97
Revises: 1306aad42810
Create Date: 2020-10-21 06:58:36.941262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406122598e97'
down_revision = '1306aad42810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
