"""initial setup

Revision ID: 40d0d971010d
Revises: d9a8a941aafa
Create Date: 2020-10-23 02:00:38.084725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d0d971010d'
down_revision = 'd9a8a941aafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
