"""initial setup

Revision ID: 422b241fec16
Revises: dda1b9e424fc
Create Date: 2020-10-24 00:24:21.156415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422b241fec16'
down_revision = 'dda1b9e424fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
