"""initial setup

Revision ID: 43be759b0ad9
Revises: 3f9472532aa9
Create Date: 2020-10-23 17:11:55.550537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43be759b0ad9'
down_revision = '3f9472532aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
