"""initial setup

Revision ID: 45a421671422
Revises: 9f5c117cfd70
Create Date: 2020-10-25 23:05:53.366911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a421671422'
down_revision = '9f5c117cfd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
