"""initial setup

Revision ID: 4e4ac9ea3c2f
Revises: 45a421671422
Create Date: 2020-10-25 23:12:42.843781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4ac9ea3c2f'
down_revision = '45a421671422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
