"""initial setup

Revision ID: 57eafc838d80
Revises: 825cbcef4f8c
Create Date: 2020-10-23 17:27:09.367050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57eafc838d80'
down_revision = '825cbcef4f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
