"""initial setup

Revision ID: 598f7df3d226
Revises: d1d860c9fa71
Create Date: 2020-10-24 22:29:47.051800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598f7df3d226'
down_revision = 'd1d860c9fa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
