"""initial setup

Revision ID: 5a4601784ee0
Revises: 27e7d54b2305
Create Date: 2020-10-21 22:42:21.806002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4601784ee0'
down_revision = '27e7d54b2305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
