"""initial setup

Revision ID: 5c5003685269
Revises: 8f0183e5b15a
Create Date: 2020-10-21 03:00:22.174237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5003685269'
down_revision = '8f0183e5b15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
