"""initial setup

Revision ID: 604ecdf71b17
Revises: e61a2070c0aa
Create Date: 2020-10-21 07:43:46.236450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604ecdf71b17'
down_revision = 'e61a2070c0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
