"""initial setup

Revision ID: 61dbf0798fbb
Revises: 57eafc838d80
Create Date: 2020-10-23 17:30:24.353830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dbf0798fbb'
down_revision = '57eafc838d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
