"""initial setup

Revision ID: 6d9d9f198c36
Revises: 3b0d7767f518
Create Date: 2020-10-21 07:47:07.022032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9d9f198c36'
down_revision = '3b0d7767f518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
