"""initial setup

Revision ID: 721d04be84bf
Revises: db0766727259
Create Date: 2020-10-21 03:18:04.943399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721d04be84bf'
down_revision = 'db0766727259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
