"""initial setup

Revision ID: 75d685cc34ba
Revises: 40d0d971010d
Create Date: 2020-10-23 09:41:51.487414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d685cc34ba'
down_revision = '40d0d971010d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
