"""initial setup

Revision ID: 78839510bab5
Revises: 881dd326e166
Create Date: 2020-10-21 05:56:48.947499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78839510bab5'
down_revision = '881dd326e166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
