"""initial setup

Revision ID: 7b2fed399de1
Revises: dd119777ad57
Create Date: 2020-10-24 00:34:41.989296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2fed399de1'
down_revision = 'dd119777ad57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
