""".

Revision ID: 81968acd3f6d
Revises: d10c4d8d4690
Create Date: 2020-03-17 06:49:43.316382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81968acd3f6d'
down_revision = 'd10c4d8d4690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
