"""initial setup

Revision ID: 825cbcef4f8c
Revises: e000f35cf3b7
Create Date: 2020-10-23 17:26:38.383480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825cbcef4f8c'
down_revision = 'e000f35cf3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
