"""initial setup

Revision ID: 881dd326e166
Revises: e77b2ddc8e19
Create Date: 2020-10-21 04:06:26.311155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881dd326e166'
down_revision = 'e77b2ddc8e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
