"""initial setup

Revision ID: 8f0183e5b15a
Revises: 146f41971c10
Create Date: 2020-10-21 02:55:36.262549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0183e5b15a'
down_revision = '146f41971c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
