"""initial setup

Revision ID: 954db9f5c665
Revises: b6df31486ffb
Create Date: 2020-10-24 19:01:10.841385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954db9f5c665'
down_revision = 'b6df31486ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
