"""initial setup

Revision ID: 962d74837db8
Revises: 404d2d085b85
Create Date: 2020-10-21 10:21:13.809081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d74837db8'
down_revision = '404d2d085b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
