"""initial setup

Revision ID: 9d02891eef61
Revises: ac8a4501d57e
Create Date: 2020-10-21 02:08:48.103621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d02891eef61'
down_revision = 'ac8a4501d57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
