"""initial setup

Revision ID: 9f5c117cfd70
Revises: 2551ccac947c
Create Date: 2020-10-25 01:36:28.042787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5c117cfd70'
down_revision = '2551ccac947c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
