"""initial setup

Revision ID: a87ce43b22f7
Revises: 0b8d28971751
Create Date: 2020-10-23 17:25:35.476678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87ce43b22f7'
down_revision = '0b8d28971751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
