"""initial setup

Revision ID: b1e60342cc2e
Revises: 78839510bab5
Create Date: 2020-10-21 06:02:10.275362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e60342cc2e'
down_revision = '78839510bab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
