"""initial setup

Revision ID: b6df31486ffb
Revises: 0c70aabcd3ee
Create Date: 2020-10-24 01:09:10.218650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6df31486ffb'
down_revision = '0c70aabcd3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
