"""initial setup

Revision ID: c5ccbab73567
Revises: 7b2fed399de1
Create Date: 2020-10-24 00:45:13.459267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ccbab73567'
down_revision = '7b2fed399de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
