"""initial setup

Revision ID: cbc62a08885d
Revises: cd65778c53b4
Create Date: 2020-10-20 12:56:00.377456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc62a08885d'
down_revision = 'cd65778c53b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
