"""initial setup

Revision ID: cc25ddd90059
Revises: f0798c6b58d1
Create Date: 2020-10-20 14:54:22.397183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc25ddd90059'
down_revision = 'f0798c6b58d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
