"""initial setup

Revision ID: d197bd834291
Revises: 2b44cedd9dff
Create Date: 2020-10-23 10:19:05.883058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd197bd834291'
down_revision = '2b44cedd9dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
