"""initial setup

Revision ID: d1d860c9fa71
Revises: 954db9f5c665
Create Date: 2020-10-24 20:39:22.387488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d860c9fa71'
down_revision = '954db9f5c665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
