"""initial setup

Revision ID: d21b3d18a5a9
Revises: 406122598e97
Create Date: 2020-10-21 07:29:32.096163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21b3d18a5a9'
down_revision = '406122598e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
