"""initial setup

Revision ID: d55368111a8c
Revises: 598f7df3d226
Create Date: 2020-10-24 23:54:52.489903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55368111a8c'
down_revision = '598f7df3d226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
