"""initial setup

Revision ID: d6a838569981
Revises: 75b9bcc6aa85
Create Date: 2020-10-26 16:57:22.901161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a838569981'
down_revision = '75b9bcc6aa85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
