"""initial setup

Revision ID: d75645794514
Revises: cc25ddd90059
Create Date: 2020-10-20 15:00:33.840524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75645794514'
down_revision = 'cc25ddd90059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
