"""initial setup

Revision ID: d9a8a941aafa
Revises: 5a4601784ee0
Create Date: 2020-10-22 01:30:18.121637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a8a941aafa'
down_revision = '5a4601784ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
