"""initial setup

Revision ID: dbd25c203031
Revises: cbc62a08885d
Create Date: 2020-10-20 13:33:48.684415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd25c203031'
down_revision = 'cbc62a08885d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
