"""initial setup

Revision ID: dd119777ad57
Revises: 422b241fec16
Create Date: 2020-10-24 00:29:26.226382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd119777ad57'
down_revision = '422b241fec16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
