"""initial setup

Revision ID: dda1b9e424fc
Revises: de9a33fc587a
Create Date: 2020-10-24 00:16:05.155317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda1b9e424fc'
down_revision = 'de9a33fc587a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
