"""initial setup

Revision ID: de9a33fc587a
Revises: 03c05318ebc9
Create Date: 2020-10-24 00:01:59.531840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9a33fc587a'
down_revision = '03c05318ebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
