"""initial setup

Revision ID: deb834364bed
Revises: 9d02891eef61
Create Date: 2020-10-21 02:23:57.793136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb834364bed'
down_revision = '9d02891eef61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
