"""initial setup

Revision ID: e000f35cf3b7
Revises: a87ce43b22f7
Create Date: 2020-10-23 17:26:11.647892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e000f35cf3b7'
down_revision = 'a87ce43b22f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
