"""initial setup

Revision ID: e61a2070c0aa
Revises: d21b3d18a5a9
Create Date: 2020-10-21 07:43:25.323471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61a2070c0aa'
down_revision = 'd21b3d18a5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
