"""initial setup

Revision ID: e77b2ddc8e19
Revises: e927aa806807
Create Date: 2020-10-21 03:38:12.717838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77b2ddc8e19'
down_revision = 'e927aa806807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
