"""initial setup

Revision ID: e927aa806807
Revises: 721d04be84bf
Create Date: 2020-10-21 03:26:17.077272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e927aa806807'
down_revision = '721d04be84bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
