"""initial setup

Revision ID: f0798c6b58d1
Revises: 1b39cfeaa1bd
Create Date: 2020-10-20 14:39:51.123540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0798c6b58d1'
down_revision = '1b39cfeaa1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
