"""added browser column to ClientHello

Revision ID: f1a7dc15552d
Revises: 4e8cee8cddd1
Create Date: 2020-08-16 00:46:23.141409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a7dc15552d'
down_revision = '4e8cee8cddd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_hello', sa.Column('browser', sa.String(), nullable=False))
    op.create_unique_constraint('ip_adress_constraint', 'proxy', ['ip_address'])
    op.drop_constraint('ip_address_constraint', 'proxy', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ip_address_constraint', 'proxy', ['ip_address'])
    op.drop_constraint('ip_adress_constraint', 'proxy', type_='unique')
    op.drop_column('client_hello', 'browser')
    # ### end Alembic commands ###
