"""initial setup

Revision ID: f6567e038fcb
Revises: 61dbf0798fbb
Create Date: 2020-10-23 23:36:07.006955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6567e038fcb'
down_revision = '61dbf0798fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
